export class CustomerDetail{
    cust_id?:number;
    title?:string;
    first_name?:string;
    middle_name?:string;
    last_name?:string;
    fathers_name?:string;
    mobile_number?:string;
    email?:string;
    aadhar?:number;
    pan_card?:string;
    pan_doc?:string;
    dob?:Date;
    occupation_type?:string;
    source_of_income?:string;
    gross_annual_income?:string;
    debit_card?:boolean;
    net_banking?:boolean;
    approval_status?:string;

    public constructor(
        cust_id:number,
        title:string,
        first_name:string,
        middle_name:string,
        last_name:string,
        fathers_name:string,
        mobile_number:string,
        email:string,
        aadhar:number,
        pan_card:string,
        pan_doc:string,
        dob:Date,
        occupation_type:string,
        source_of_income:string,
        gross_annual_income:string,
        debit_card:boolean,
        net_banking:boolean,
        approval_status:string,
    )
    {
        this.cust_id=cust_id
        this.title=title
        this.first_name=first_name
        this.middle_name=middle_name
        this.last_name=last_name
        this.fathers_name=fathers_name
        this.mobile_number=mobile_number
        this.email=email
        this.aadhar=aadhar
        this.pan_card=pan_card
        this.pan_doc=pan_doc
        this.dob=dob
        this.occupation_type=occupation_type
        this.source_of_income=source_of_income
        this.gross_annual_income=gross_annual_income
        this.debit_card=debit_card
        this.net_banking=net_banking
        this.approval_status=approval_status
    }
}